# EasyBot Velocity 配置文件

# 服务器名称
server_name = "velocity_server"

# 服务URL (WebSocket连接地址)
service_url = "ws://127.0.0.1:8080/bridge"

# 认证令牌
token = ""

# 聊天同步设置
sync_chat = true
sync_join_leave = true

# 调试模式
debug = false

# 消息格式
chat_format = "&b[MC] &e{player_name}&r: {message}"
join_format = "&e{player_name} &a加入了服务器"
leave_format = "&e{player_name} &c离开了服务器"

# 绑定成功消息
bind_success_message = "§f[§a!§f] 绑定§f §a#account §f(§a#name§f) 成功!"

# 绑定成功事件
enable_success_event = false
bind_success_commands = []

# @功能设置
enable_at_find = true
enable_at_event = true

# 强制绑定设置
force_bind_enabled = false
force_bind_kick_message = "§c您的QQ账号已解绑，需要重新绑定才能继续游戏！"
deny_on_bind_check_fail = true
